# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170904_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='media/events/', width_field='width_field'),
        ),
    ]
