# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20170911_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='events/', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='event',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
