# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20171001_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='height_field',
            field=models.IntegerField(default=290),
        ),
        migrations.AlterField(
            model_name='event',
            name='width_field',
            field=models.IntegerField(default=210),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='height_field',
            field=models.IntegerField(blank=True, default=290),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='width_field',
            field=models.IntegerField(blank=True, default=210),
        ),
    ]
