# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import team.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=50)),
                ('pic', models.ImageField(blank=True, height_field='height_field', upload_to=team.models.upload_location, width_field='width_field')),
                ('github_link', models.URLField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('linkedin', models.CharField(max_length=250)),
                ('description', models.URLField(max_length=250)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
