# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20170910_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='height_field',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='width_field',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
