# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 18:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0003_auto_20170910_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='user_id',
        ),
        migrations.AddField(
            model_name='team',
            name='user_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
