# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20170911_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='year',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='pic',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='team/', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
