# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('adm_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('contact_no', models.BigIntegerField()),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Event')),
            ],
        ),
    ]
